name: Check keywords.txt

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-keywords-txt.yml"
      - "keywords.txt"
  pull_request:
    paths:
      - ".github/workflows/check-keywords-txt.yml"
      - "keywords.txt"
  workflow_dispatch:
  repository_dispatch:

jobs:
  extra-library-checks:
    runs-on: ubuntu-latest

    env:
      ARDUINO_CI_SCRIPT_FOLDER: extras/ci-tools/arduino-ci-script

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install arduino-ci-script
        uses: per1234/install-arduino-ci-script-action@main
        with:
          installation-path: ${{ env.ARDUINO_CI_SCRIPT_FOLDER }}

      # See: https://github.com/per1234/arduino-ci-script#check_keywords_txt-searchpath-maximumsearchdepth
      - name: Check keywords.txt
        run: |
          source "${ARDUINO_CI_SCRIPT_FOLDER}/arduino-ci-script.sh"
          check_keywords_txt "$GITHUB_WORKSPACE"
